-- 品牌表
create table prod_brand {
  BRAND_ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '品牌ID',
  CATEGORY_ID BIGINT NOT NULL DEFAULT 0 COMMENT '类目ID',
  BRAND_NAME VARCHAR(100) NOT NULL DEFAULT '' COMMENT '品牌名称',
  BRAND_DESC VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '品牌介绍',
  BRAND_LOGO_URL VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '品牌LOGO',
  STATUS INT(5) NOT NULL DEFAULT 0 COMMENT '状态',
  BRAND_OFFICE_ADDR VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '品牌官方地址',
  BRAND_STORY VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '品牌故事',
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
}