-- 产品基本属性表
create table prod_base_props {
  ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
  PROD_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '产品ID',
  PROP_NAME_ID BIGINT NOT NULL DEFAULT 0 COMMENT '属性名ID',
  PROP_VALUE_ID BIGINT NOT NULL DEFAULT 0 COMMENT '属性值ID',
  IS_SKU BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否SKU',
  SKU_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'SKU_ID',
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
}