!--产品表
create table prod {
  PROD_ID VARCHAR(50) NOT NULL DEFAULT '' PRIMARY KEY COMMENT '产品ID',
  PROD_NAME VARCHAR(200) NOT NULL DEFAULT '' COMMENT '产品名称',
  BRAND_ID BIGINT NOT NULL DEFAULT 0 COMMENT '品牌ID',
  LIST_PRICE DOUBLE NOT NULL DEFAULT 0.01 COMMENT '列表价格',
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
}