-- 计量属性表
create table BASE_PRICE (
  ID bigint primary key auto_increment COMMENT 'ID',
  PROD_HASH VARCHAR(100) NOT NULL DEFAULT '' COMMENT '产品属性HASH',
  SINGLE_PRICE INT(20) NOT NULL DEFAULT 0 COMMENT '产品单价',
  USER_ID bigint NOT NULL DEFAULT 0 COMMENT '商户号',
  STATUS INT(2) NOT NULL DEFAULT 0 COMMENT '状态',
  PROD_STR VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '产品属性字符串',
  CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
)